{ config, pkgs, ... }: 

{
    # Import other configuration modules
    # (hardware-configuration.nix is autogenerated upon installation)
    # paths in nix expressions are always relative the file which defines them
    imports = [
        ./hardware-configuration.nix
    ];

    # Name your host machine
    networking.hostName = "KingJalyn"; 

    # Set your time zone.
    time.timeZone = "America/Chicago";

    # Enter keyboard layout
    services.xserver.layout = "us";
    services.xserver.xkbVariant = "altgr-intl";

    # Define user accounts
    users.users.charity = {
      extraGroups = [ "wheel" "networkmanager" ];
      isNormalUser = true;
    };
    
    # Install some packages
    environment.systemPackages = with pkgs; [
			agenix
			vim
    ]; 
 
    # Enable the OpenSSH daemon
    services.openssh.enable = true;
    services.openssh.passwordAuthentication = false;

		# Enable firewall and allow traffic in for Traefik, SSH, and Headscale
		networking.firewall.enable = true;
		networking.firewall.allowedTCPPorts = [ 22 80 443 ];
		networking.firewall.allowedUDPPorts = [ 51820 ]; # for Headscale/WireGuard

		# Enable Podman for docker containers
		virtualisation.podman.enable = true;
		users.groups.podman = {charity};

		# Enable Traefik
		services.traefik.enable = true;
		services.traefik.acme.email = "verse-upbeat-void@duck.com"; # for Let's Encrypt
		services.traefik.entryPoints = [ "web" "websecure" ];

		# Enable Headscale
		services.headscale.enable = true;

		# Turn on auto-updates and require pw for sudo use
		security.autoUpgrade.enable = true;
		security.sudo.wheelNeedsPassword = true;
}